# Application Settings
data_dir: "./data/dataset_heart.csv"
model_dir: "./models"
model_params_path: "./config/model_params.yaml"
experiment_name: "Heart Disease Classification"

# AWS/LocalStack Settings
s3:
  bucket_name: "heart-disease-models"
  endpoint_url: "http://localhost:4566"  # LocalStack default endpoint
  access_key_id: "test"
  secret_access_key: "test"
  region_name: "us-east-1"

# MLflow Settings
mlflow:
  tracking_uri: "sqlite:///data/mlflow.db"

# Model Training Settings
train_test_split:
  test_size: 0.2
  random_state: 42

model:
  dir: "models"
  version: "1.0.0"

data:
  version: "1.0.0"

MODEL_PARAMS:
  logistic_regression:
    C: 1.0
    penalty: 'l2'
    solver: 'liblinear'
    max_iter: 1000

  svm:
    C: 1.0
    kernel: 'rbf'
    probability: true

  knn:
    n_neighbors: 5
    weights: 'uniform'

  mlp:
    hidden_layer_sizes: [100, 50]
    activation: 'relu'
    solver: 'adam'
    max_iter: 1000

  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1

  extra_trees:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1

  catboost:
    iterations: 100
    depth: 6
    learning_rate: 0.1
    loss_function: 'Logloss'

  lgbm:
    num_leaves: 31
    max_depth: -1
    learning_rate: 0.1
    n_estimators: 100

  xgboost:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: 'binary:logistic'
