FROM python:3.12-slim

WORKDIR /app

# Copy only the necessary files for training
COPY pyproject.toml .
COPY config/ ./config/
COPY data/ ./data/
COPY src/ ./src/
COPY main.py .

# Install dependencies
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

# Set environment variables
ENV PYTHONPATH=/app

# Run the training script
CMD ["python", "main.py"]
