version: '3'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./models:/app/models
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    depends_on:
      - train

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  models:
