version: "3.7"

volumes:
  grafana_data: {}
  models: {}
  mlflow_data: {}
  localstack_data: {}
  postgres_data: {}  # Added for database persistence

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Added for data persistence
    networks:
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier
    depends_on:
      - db

  grafana:
    image: grafana/grafana-enterprise
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/opt/grafana/dashboards
    networks:
      - back-tier
      - front-tier
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    image: heart-disease-train:latest
    volumes:
      - ./models:/app/models
    networks:
      - back-tier
    depends_on:
      - db
      - localstack
      - mlflow

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: heart-disease-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    depends_on:
      - train
      - db
      - localstack
      - mlflow
    networks:
      - back-tier
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: heart-disease-streamlit:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - front-tier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
