services:
  
  db:
    container_name: heart-disease-postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: heart-disease-adminer
    image: adminer
    ports:
      - "8080:8080"

  grafana:
    container_name: heart-disease-grafana
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-config:/etc/grafana/provisioning

  localstack:
    container_name: heart-disease-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  mlflow:
    container_name: heart-disease-mlflow
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mlflow
    image: heart-disease-mlflow:latest
    ports:
      - "6060:6060"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow_data:/data

  train:
    container_name: heart-disease-train
    build:
      context: .
      dockerfile: ./docker/Dockerfile.train
    image: heart-disease-train:latest
    volumes:
      - ./models:/app/models
      - ./mlflow_data:/data
      - ./mlruns:/app/mlruns

  api:
    container_name: heart-disease-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    image: heart-disease-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    container_name: heart-disease-streamlit
    build:
      context: .
      dockerfile: ./docker/Dockerfile.streamlit
    image: heart-disease-streamlit:latest
    ports:
      - "8501:8501"

volumes:
  postgres_data:
  grafana_data:
  models:
  mlflow_data:
  localstack_data:

networks:
  default:
    driver: bridge
