version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-config:/etc/grafana/provisioning

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "6060:6060"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow_data:/data

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./models:/app/models
      - ./mlflow_data:/data
      - ./mlruns:/app/mlruns

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"

volumes:
  postgres_data:
  grafana_data:
  models:
  mlflow_data:
  localstack_data:

networks:
  default:
    driver: bridge
